import { FC, useCallback } from 'react';
import {
  Drawer,
  Form,
  Button,
  Alert,
  Spin,
  Divider,
} from 'antd';
import {
  DetailedDocumentResponse,
  FieldAttribute,
  RelationAttribute,
  isRelationAttribute,
  ProblemDetails,
} from '@/api/types';
import { useCreateDocument } from '@/api/hooks';
import { RelationField } from './RelationField';
import { DocumentFormField } from './DocumentFormField';
import { getTypeName, coerceValue } from './helpers';

export interface CreateDocumentDrawerProps {
  open: boolean;
  onClose: () => void;
  schema: DetailedDocumentResponse;
  apiId: string;
}

export const CreateDocumentDrawer: FC<CreateDocumentDrawerProps> = ({
  open,
  onClose,
  schema,
  apiId,
}) => {
  const [form] = Form.useForm();
  const mutation = useCreateDocument(apiId);

  const localizations: string[] = schema.options?.localizations ?? [];

  const onFinish = useCallback(
    (values: Record<string, unknown>) => {
      const data: Record<string, unknown> = {};

      for (const attr of schema.attributes) {
        if (isRelationAttribute(attr)) {
          const val = values[attr.id];
          if (val !== undefined && val !== null) {
            const ids = Array.isArray(val) ? val : [val];
            if (ids.length > 0) {
              data[attr.id] = { connect: ids };
            }
          }
        } else {
          const typeName = getTypeName(attr.type);
          // uuid is hidden from the form and generated by the backend
          if (typeName === 'uuid') continue;

          const raw = values[attr.id];
          if (raw === undefined || raw === null) continue;

          data[attr.id] = coerceValue(typeName, raw);
        }
      }

      mutation.mutate(
        { data },
        {
          onSuccess: () => {
            form.resetFields();
            onClose();
          },
        },
      );
    },
    [form, mutation, onClose, schema.attributes],
  );

  const error = mutation.error as ProblemDetails | null;
  const errorMessage = error
    ? `${error.title ?? 'Error'}: ${error.detail ?? 'An unexpected error occurred.'}`
    : null;

  const footer = (
    <div style={{ display: 'flex', justifyContent: 'flex-end', gap: 8 }}>
      <Button
        onClick={() => {
          form.resetFields();
          mutation.reset();
          onClose();
        }}
      >
        Cancel
      </Button>
      <Button
        type="primary"
        loading={mutation.isPending}
        onClick={() => form.submit()}
      >
        Create {schema.info.singularName}
      </Button>
    </div>
  );

  return (
    <Drawer
      title={`Create New ${schema.info.title}`}
      placement="right"
      width={600}
      open={open}
      onClose={() => {
        form.resetFields();
        mutation.reset();
        onClose();
      }}
      footer={footer}
      destroyOnHidden
    >
      {errorMessage && (
        <Alert
          type="error"
          message={errorMessage}
          showIcon
          closable
          onClose={() => mutation.reset()}
          style={{ marginBottom: 20 }}
        />
      )}

      <Form
        form={form}
        layout="vertical"
        onFinish={onFinish}
        scrollToFirstError
      >
        {/* Field attributes */}
        {schema.attributes
          .filter((a) => !isRelationAttribute(a))
          .map((attr) => (
            <DocumentFormField
              key={attr.id}
              attr={attr as FieldAttribute}
              localizations={localizations}
            />
          ))}

        {/* Relation attributes */}
        {schema.attributes.some((a) => isRelationAttribute(a)) && (
          <>
            <Divider titlePlacement="left" plain style={{ fontSize: 12, color: '#6b7280' }}>
              Relations
            </Divider>
            {schema.attributes
              .filter((a) => isRelationAttribute(a))
              .map((attr) => (
                <RelationField key={attr.id} attr={attr as RelationAttribute} />
              ))}
          </>
        )}

        {mutation.isPending && (
          <div style={{ textAlign: 'center', padding: '16px 0' }}>
            <Spin tip="Creating…" />
          </div>
        )}
      </Form>
    </Drawer>
  );
};
